export interface LabApiResponse<T> { success: boolean; statusCode: number; message: string; data: T | null; errors?: string[]; }
export interface LabDashboard { todayOrders: number; pendingCollection: number; processing: number; verificationPending: number; reportsToday: number; statOpen: number; criticalUnacknowledged: number; }
export interface LabTest { id: string; code: string; name: string; shortName: string; category: string; department: string; sampleTypeId: string | null; sampleType: string | null; containerId: string | null; container: string | null; tatMinutes: number; chargeMasterId: string | null; serviceCode: string | null; price: number; isActive: boolean; parameterCount: number; }
export interface LabParameter { id: string; testId: string; code: string; name: string; dataType: string; unit: string | null; decimalPlaces: number; selectionOptionsJson: string | null; criticalLow: number | null; criticalHigh: number | null; displayOrder: number; isActive: boolean; }
export interface LabTestDetail { test: LabTest; parameters: LabParameter[]; referenceRanges: unknown[]; }
export interface LabOrder { id: string; orderNumber: string; patientId: string; patientName: string; medicalRecordNo: string; encounterId: string | null; doctorName: string | null; sourceModule: string; priority: string; clinicalNotes: string | null; statusCode: string; orderedAt: string; itemCount: number; }
export interface PendingCollection { orderId: string; orderNumber: string; patientId: string; patientName: string; medicalRecordNo: string; sourceModule?: string; priority: string; statusCode?: string; orderedAt: string; tests: string; itemCount?: number; }
export interface LabWorkItem { processingId: string; orderItemId: string; sampleId: string; sampleNumber: string; orderNumber: string; patientName: string; medicalRecordNo: string; testId: string; testName: string; department: string; priority: string; statusCode: string; technicianId: string | null; technicianName: string | null; startedAt: string | null; }
export interface VerificationItem { resultId: string; orderNumber: string; patientName: string; medicalRecordNo: string; testName: string; sampleNumber: string; technicianName: string | null; submittedAt: string; hasCritical: boolean; }
export interface LabReport { id: string; reportNumber: string; orderId: string; orderNumber: string; patientId: string; patientName: string; medicalRecordNo: string; currentVersion: number; statusCode: string; releasedAt: string; }
export interface CriticalResult { id: string; orderNumber: string; patientName: string; medicalRecordNo: string; testName: string; parameterName: string; value: string; unit: string | null; notificationSent: boolean; acknowledgedAt: string | null; acknowledgedBy: string | null; createdAt: string; }
export interface LabMaster { id: string; code: string; name: string; isActive: boolean; displayOrder: number; }
export interface OrderOptions { patients: Array<{ id: string; medicalRecordNo: string; name: string }>; doctors: Array<{ id: string; name: string; registrationNo: string }>; }
export interface LabResultDetail { header: { id: string; testId: string; testName: string; patientName: string; medicalRecordNo: string; sampleNumber: string; orderNumber: string; statusCode: string; comments: string | null }; parameters: Array<{ parameterId: string; code: string; name: string; dataType: string; unit: string | null; decimalPlaces: number; selectionOptionsJson: string | null; numericValue: number | null; textValue: string | null; booleanValue: boolean | null; selectionValue: string | null; richValue: string | null; referenceRange: string | null; flag: string | null; isCritical: boolean; comment: string | null }>; }
