const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/app/features/billing/billing-document.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:exportsObject});const {billingDocumentHtml:render,rupeesInWords:words}=exportsObject;
const header={hospitalName:'Auspira Care360',branchName:'Alpha-Moshi',hospital:{hospitalName:'Auspira Hospital',address:{addressLine1:'Hospital Road',cityName:'Pune',stateName:'Maharashtra',postalCode:'411001'},contact:{primaryPhone:'123',email:'billing@example.invalid'}}};
const detail={invoice:{invoiceNo:'INV-1',patientName:'Siddharth Patil',medicalRecordNo:'MRN-002',invoiceDate:'2026-10-08T03:30:00Z',invoiceType:'OPD',grossAmount:1300,discountAmount:0,taxAmount:0,netAmount:1300,paidAmount:500,dueAmount:800,statusCode:'PARTIALLY_PAID'},items:[{description:'Consultation',serviceCode:'OPD001',quantity:1,unitPrice:1300,discountAmount:0,taxAmount:0,netAmount:1300}],payments:[]};
const receipt={receiptNo:'RCP-1',invoiceNo:'INV-1',paymentNo:'PAY-1',patientName:'Siddharth Patil',medicalRecordNo:'MRN-002',amount:500,paymentMode:'CASH',issuedAt:'2026-10-08T03:30:00Z',statusCode:'ACTIVE'};
test('receipt distinguishes this payment from invoice totals and balance',()=>{const html=render(header,detail,receipt);assert.ok(html.includes('This payment'));assert.ok(html.includes('Balance due'));assert.ok(html.includes('Rupees Five Hundred Only'));assert.ok(html.includes('Consultation'));assert.ok(html.includes('Auspira Hospital'));assert.ok(html.includes('8 Oct 2026'));assert.ok(!html.includes('Tax Invoice'));});
test('INR words use lakh/crore grouping and correct paise rounding',()=>{assert.equal(words(1300),'Rupees One Thousand Three Hundred Only');assert.equal(words(123456.78),'Rupees One Lakh Twenty Three Thousand Four Hundred Fifty Six and Seventy Eight Paise Only');assert.equal(words(99.999),'Rupees One Hundred Only');assert.equal(words(0),'Rupees Zero Only');});
test('print layout uses A4, repeated table headers, no fixed overlapping footer, and escapes records',()=>{const html=render(header,{...detail,items:[{...detail.items[0],description:'<script>alert(1)</script>'}]},receipt);assert.ok(html.includes('size:A4'));assert.ok(html.includes('display:table-header-group'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('position:fixed'));});
test('receipt remains printable without invoice lookup data',()=>{const html=render(header,null,receipt);assert.ok(html.includes('RCP-1'));assert.ok(html.includes('This payment'));assert.ok(!html.includes('Balance due'));});
