const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function moduleExports(path){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports});return exports;}
const {savedPatientPrescriptionPreview:map}=moduleExports('src/app/features/patients/patient-prescription-document.ts');
const {printablePrescriptionHtml:render,defaultPrescriptionPrintOptions:options}=moduleExports('src/app/features/opd/prescription-document.ts');
const patient={patientGuid:'patient-1',fullName:'Siddharth Patil',medicalRecordNo:'MRN-002',age:24,genderName:'Male',knownAllergies:null};
const legacy={prescriptionNo:'RX-1',details:{context:[{label:'Status',value:'Finalized'}],vitals:[],medicines:[],investigations:[],procedures:[],advice:[],dietAdvice:[],followUp:[]}};
const clinical={prescriptionId:'rx-1',prescriptionNo:'RX-2026-1',includeVitalsInPrescription:true,vitals:{bloodPressure:'120/80'},complaints:[{complaint:'Pain'}],diagnoses:[{diagnosisName:'Back pain'}],prescriptions:[{medicine:'Sample medicine',strength:'5 mg',dosageForm:'Tablet',dosage:'1 tablet',frequency:'BD',route:'Oral',duration:'3',quantity:'6',instructions:'After food'}],adviceList:['Rest'],dietAdviceList:[],prescriptionInvestigations:['CBC'],followUp:{followUpRequired:true,followUpDate:'2026-10-11',reason:'Review',notes:'Review pain'}};
const saved={id:'rx-1',consultationId:'visit-1',clinicalData:JSON.stringify(clinical),instructions:'',status:'FINALIZED',createdAt:'2026-10-08T03:30:00Z',doctorName:'Dr. Shree',qualification:'MBBS',registrationNo:'REG-1',department:'General Medicine',branchName:'Alpha-Moshi',investigations:['CBC']};
test('patient prescription uses saved OPD clinical fields and authoritative doctor',()=>{const p=map(patient,saved,null,'Hospital',legacy);assert.equal(p.doctorName,'Dr. Shree');assert.equal(p.diagnosisSummary,'Back pain');assert.equal(p.medicines[0].dosage,'1 tablet');assert.equal(p.vitals[0].value,'120/80');assert.equal(p.investigations.length,1);assert.ok(p.followUp.some(x=>x.includes('11')));});
test('same shared document preserves medication columns and escapes patient content',()=>{const p=map({...patient,fullName:'<script>alert(1)</script>'},saved,null,'Hospital',legacy);const html=render(p,false,options());assert.ok(html.includes('Medicine / Strength'));assert.ok(html.includes('3 days'));assert.ok(html.includes('After food'));assert.ok(html.includes('Dr. Shree'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));});
test('a later clinical prescription does not replace the requested historical one',()=>{const p=map(patient,{...saved,clinicalData:JSON.stringify({...clinical,prescriptionId:'other-rx'})},null,'Hospital',legacy);assert.equal(p.medicines.length,0);});
test('vitals and investigations respect the OPD inclusion choices',()=>{const p=map(patient,{...saved,clinicalData:JSON.stringify({...clinical,includeVitalsInPrescription:false,includeInvestigationsInPrescription:false})},null,'Hospital',legacy);assert.equal(p.vitals.length,0);assert.equal(p.investigations.length,0);});
