export type PharmacyTab = 'dashboard' | 'prescriptions' | 'dispensing' | 'medicines' | 'formulary' | 'interactions' | 'allergies' | 'stock';
export interface PharmacyDashboard { pendingPrescriptions: number; dispensedToday: number; salesToday: number; lowStockItems: number; expiringBatches: number; expiredBatches: number; stockValue: number; recentDispensings: RecentDispensing[]; }
export interface RecentDispensing { id: string; dispenseNumber: string; patientName: string; medicalRecordNo: string; totalAmount: number; statusCode: string; dispensedAt: string; }
export interface PrescriptionQueueItem { id: string; prescriptionNumber: string; statusCode: string; prescribedAt: string; patientId: string; patientName: string; medicalRecordNo: string; doctorName: string | null; encounterId: string; itemCount: number; availableItemCount: number; }
export interface PrescriptionItem { id: string; medicineId: string | null; medicineName: string; dosage: string; frequency: string; days: number; medicineCode: string | null; genericName: string | null; unit: string | null; availableQuantity: number; }
export interface PrescriptionDetail { header: PrescriptionQueueItem; items: PrescriptionItem[]; }
export interface Medicine { id: string; code: string; name: string; genericDrugId: string | null; genericName: string; dosageFormId: string | null; dosageForm: string; strength: string; routeId: string | null; route: string; unit: string; manufacturerId: string | null; manufacturer: string | null; therapeuticCategoryId: string | null; category: string; packSize: number; reorderLevel: number; salePrice: number; taxPercent: number; prescriptionRequired: boolean; notes: string | null; isFormulary: boolean; isControlled: boolean; requiresColdChain: boolean; isActive: boolean; stockOnHand: number; }
export interface StockBatch { batchId: string; medicineId: string; medicineCode: string; medicineName: string; genericName: string; batchNumber: string; locationName: string | null; expiryDate: string; availableQuantity: number; purchasePrice: number; mrp: number; salePrice: number; reorderLevel: number; isQuarantined: boolean; stockState: string; }
export interface SaveMedicineRequest { code: string; name: string; genericDrugId: string; dosageFormId: string; strength: string; routeId: string; unit: string; manufacturerId: string | null; therapeuticCategoryId: string; packSize: number; reorderLevel: number; salePrice: number; taxPercent: number; prescriptionRequired: boolean; notes: string; isFormulary: boolean; isControlled: boolean; requiresColdChain: boolean; isActive: boolean; }
export interface GenericDrug { id: string; code: string; name: string; therapeuticCategoryId: string | null; therapeuticCategory: string | null; description: string | null; isActive: boolean; brandCount: number; }
export interface DrugMasterOption { id: string; code: string; name: string; isActive: boolean; }
export interface DrugMasterOptions { genericDrugs: GenericDrug[]; dosageForms: DrugMasterOption[]; routes: DrugMasterOption[]; therapeuticCategories: DrugMasterOption[]; manufacturers: DrugMasterOption[]; }
export interface SaveGenericDrugRequest { code: string; name: string; therapeuticCategoryId: string; description: string; isActive: boolean; }
export type FormularyStatus = 'APPROVED' | 'RESTRICTED' | 'NON_FORMULARY' | 'BLOCKED';
export interface FormularyPolicy { id: string; medicineId: string; drugCode: string; drugName: string; strength: string; genericName: string; statusCode: FormularyStatus; allDepartmentsAllowed: boolean; restrictionReason: string | null; alternativeMedicineId: string | null; alternativeMedicineName: string | null; approvalRequired: boolean; approvalRole: string | null; effectiveFrom: string; effectiveTo: string | null; notes: string | null; allowedDepartments: string[]; }
export interface FormularyOptions { departments: string[]; drugs: Array<{ id: string; code: string; name: string; strength: string }>; }
export interface SaveFormularyPolicyRequest { statusCode: FormularyStatus; allDepartmentsAllowed: boolean; allowedDepartments: string[]; restrictionReason: string; alternativeMedicineId: string | null; approvalRequired: boolean; approvalRole: string; effectiveFrom: string; effectiveTo: string | null; notes: string; }
export type DrugInteractionSeverity = 'MINOR' | 'MODERATE' | 'MAJOR' | 'CONTRAINDICATED';
export type DrugInteractionBehavior = 'INFORM' | 'WARN' | 'REQUIRE_OVERRIDE' | 'BLOCK';
export interface DrugInteractionRule { id: string; genericDrugAId: string; genericDrugACode: string; genericDrugAName: string; genericDrugBId: string; genericDrugBCode: string; genericDrugBName: string; severity: DrugInteractionSeverity; behaviorCode: DrugInteractionBehavior; description: string; clinicalRecommendation: string; isActive: boolean; reviewedBy: string | null; reviewedAt: string | null; reviewNotes: string | null; updatedAt: string | null; }
export interface DrugInteractionOptions { genericDrugs: Array<{ id: string; code: string; name: string }>; severities: DrugInteractionSeverity[]; behaviors: DrugInteractionBehavior[]; }
export interface SaveDrugInteractionRequest { genericDrugAId: string; genericDrugBId: string; severity: DrugInteractionSeverity; behaviorCode: DrugInteractionBehavior; description: string; clinicalRecommendation: string; reviewNotes: string; isActive: boolean; }
export type DrugAllergyBehavior = 'REQUIRE_OVERRIDE' | 'BLOCK';
export interface DrugAllergyMapping { id: string; genericDrugId: string; genericDrugCode: string; genericDrugName: string; allergenName: string; allergenAliases: string[]; behaviorCode: DrugAllergyBehavior; clinicalRecommendation: string; isActive: boolean; reviewedBy: string | null; reviewedAt: string | null; reviewNotes: string | null; updatedAt: string | null; }
export interface DrugAllergyMappingOptions { genericDrugs: Array<{ id: string; code: string; name: string }>; behaviors: DrugAllergyBehavior[]; }
export interface SaveDrugAllergyMappingRequest { genericDrugId: string; allergenName: string; allergenAliases: string[]; behaviorCode: DrugAllergyBehavior; clinicalRecommendation: string; reviewNotes: string; isActive: boolean; }
export interface ReceiveBatchRequest { medicineId: string; batchNumber: string; expiryDate: string; quantity: number; purchasePrice: number; mrp: number; salePrice: number; locationId: string | null; }
export interface DispenseLine { prescriptionItemId: string; medicineId: string; batchId: string; quantity: number; }
